name: smandaapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  convex_bottom_bar: 3.2.0
  firebase_core: 2.25.4
  cloud_firestore: ^4.15.4
  firebase_storage: 11.6.5
  firebase_auth: 4.17.4
  dropdown_search: 5.0.6
  image_picker: 1.0.7
  intl: 0.19.0
  flutter_barcode_scanner: 2.0.0
  geolocator: 11.0.0
  geocoding: 2.2.0
  fl_chart: 0.66.2
  dcdg: 4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/icon/icon2.png
  ios: true

flutter:
  assets:
    - assets/logo/
  uses-material-design: true
